// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/copilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/copilot">> = Specific
  const handler = {} as typeof import("../../app/copilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investigations/[caseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investigations/[caseId]">> = Specific
  const handler = {} as typeof import("../../app/investigations/[caseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investigations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investigations">> = Specific
  const handler = {} as typeof import("../../app/investigations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/evidence">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/report-html/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/report-html">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/report-html/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/report-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/report-preview">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/report-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/report">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/stages/[stage]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/stages/[stage]/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/stages/[stage]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/stages/[stage]/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/stages/[stage]/revalidate">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/stages/[stage]/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/stages/[stage]/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/stages/[stage]/unlock">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/stages/[stage]/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases">> = Specific
  const handler = {} as typeof import("../../app/api/cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/copilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/copilot">> = Specific
  const handler = {} as typeof import("../../app/api/copilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/overview">> = Specific
  const handler = {} as typeof import("../../app/api/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/telemetry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/telemetry">> = Specific
  const handler = {} as typeof import("../../app/api/telemetry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../app/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
